model:
  arch: llava_interleave
  llama_model: llava-hf/llava-onevision-qwen2-7b-si-hf
  video_input: 'mean'
  gradient_checkpointing: True
  pooling: clipST_3d
  clip_weight: /home/thr/code/S3/siglip-so400m-patch14-384
  pooling_kernel: (1,3,3)
  pooling_stride: (1,3,3)
  image_pooling_kernel: (1,3,3)
  image_pooling_stride: (1,3,3)
  frame_shape: (27,27)
  freeze_vproj: False
  freeze_tproj: False
  freeze_text: False
  btadapter: False
  long_clip: True
  freeze_LLM: False
  pad_token_id: 0
  onlyLLM: True
  ckpt: ./ckpt/checkpoint_sft

datasets:
 {}

run:
  task: interleave_sft
  bf16: False
  fp16: True
  tf32: False
  output_dir: "./physvlm/output/dpo/dpo_result_glitches"
  #cache_dir: './cache'
  version: 'v1'
  dpo_alpha: 1.0
  beta: 0.1
  gamma: 0
  training_modal: 'video'
  data_path: '/home/thr/code/S3/PhysGame_clean/dpo_10k_final.json' 
  video_folder: '/home/thr/code/S3/GamePhysics/GamePhysics'
  image_aspect_ratio: 'pad'
  group_by_modality_length: False
  lazy_preprocess: True
  num_train_epochs: 2
  dataloader_num_workers: 4
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  evaluation_strategy: "no"
  learning_rate: 5e-6
  weight_decay: 0.
  warmup_ratio: 0.1
  lr_scheduler_type: 'linear'
  logging_steps: 1
  model_max_length: 2048
  save_strategy: "steps" 
  save_steps: 25
  save_total_limit: 100
  save_only_model: True 
  deepspeed: 'physvlm/train/zero2.json'
  num_frames: 16
